# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GEDIexplorer
                                 A QGIS plugin
 this plugin will extract user selected data from GEDI file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-22
        copyright            : (C) 2022 by Kyaw Naing Win
        email                : kyawnaingwinknw@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GEDIexplorer class from file GEDIexplorer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gedi_explorer import GEDIexplorer
    return GEDIexplorer(iface)
